server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_NOTIFICATION_URL}
    username: ${DB_NOTIFICATION_USERNAME}
    password: ${DB_NOTIFICATION_PASSWORD}
    driver-class-name: ${DB_NOTIFICATION_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${JPA_GENERATION}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    topics:
      order-placement: ${KAFKA_TOPIC_ORDER_PLACEMENT}
    template:
      default-topic: ${spring.kafka.topics.order-placement}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_GROUP_ID}
      properties:
        spring:
          json:
            type:
              mapping: event:com.denisenko.event.OrderEvent