apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.orderService.secret.name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  db_order_url: {{ include "ordering.fullOrderDBUrl" . | b64enc }}
  db_order_name: {{ .Values.orderService.database.name | b64enc }}
  db_order_username: {{ .Values.orderService.database.username | b64enc }}
  db_order_password: {{ .Values.orderService.database.password | b64enc }}
  db_order_driver_class_name: {{ .Values.orderService.database.driverClassName | b64enc }}
  order_topic_user_creation: {{ .Values.orderService.kafka.topics.userCreation | b64enc }}
  order_topic_order_placement: {{ .Values.orderService.kafka.topics.orderPlacement | b64enc }}