apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.notificationService.secret.name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  db_notification_url: {{ include "ordering.fullNotificationDBUrl" . | b64enc }}
  db_notification_name: {{ .Values.notificationService.database.name | b64enc }}
  db_notification_username: {{ .Values.notificationService.database.username | b64enc }}
  db_notification_password: {{ .Values.notificationService.database.password | b64enc }}
  db_notification_driver_class_name: {{ .Values.notificationService.database.driverClassName | b64enc }}
  notification_topic_order_placement: {{ .Values.notificationService.kafka.topics.orderPlacement | b64enc }}
  notification_group_id: {{ .Values.notificationService.kafka.groupId | b64enc }}