apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.billingService.secret.name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  db_billing_url: {{ include "ordering.fullBillingDBUrl" . | b64enc }}
  db_billing_name: {{ .Values.billingService.database.name | b64enc }}
  db_billing_username: {{ .Values.billingService.database.username | b64enc }}
  db_billing_password: {{ .Values.billingService.database.password | b64enc }}
  db_billing_driver_class_name: {{ .Values.billingService.database.driverClassName | b64enc }}
  billing_topic_user_creation: {{ .Values.billingService.kafka.topics.userCreation | b64enc }}
  billing_group_id: {{ .Values.billingService.kafka.groupId | b64enc }}