apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.billingService.database.service.name }}
spec:
  selector:
    app: {{ include "ordering.fullname" . }}-ss-db-billing
  ports:
    - protocol: TCP
      port: {{ .Values.billingService.database.service.port }}
      targetPort: {{ .Values.billingService.database.image.port }}