apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.billingService.service.name }}
spec:
  type: {{ .Values.billingService.service.type }}
  ports:
    - name: web
      port: {{ .Values.billingService.service.port }}
      targetPort: {{ .Values.billingService.image.port }}
      protocol: TCP
  selector:
    app: billing-service
