apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orderService.service.name }}
spec:
  type: {{ .Values.orderService.service.type }}
  ports:
    - name: web
      port: {{ .Values.orderService.service.port }}
      targetPort: {{ .Values.orderService.image.port }}
      protocol: TCP
  selector:
    app: order-service
