apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ordering.fullname" . }}-changelog-config
  annotations:
    "helm.sh/hook": pre-install
data:
  changelog_order: |
    {{ .Values.migration.changelog.dbOrder | nindent 4 }}
  changelog_billing: |
    {{ .Values.migration.changelog.dbBilling | nindent 4 }}
  changelog_notification: |
    {{ .Values.migration.changelog.dbNotification | nindent 4 }}
