apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.billingService.configmap.name }}
  annotations:
    "helm.sh/hook": pre-install
data:
  billing_port: {{ .Values.billingService.image.port | quote }}
  billing_jpa_generation: {{ .Values.billingService.jpa.hibernate.ddlAuto }}