server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_BILLING_URL}
    username: ${DB_BILLING_USERNAME}
    password: ${DB_BILLING_PASSWORD}
    driver-class-name: ${DB_BILLING_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${JPA_GENERATION}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    topics:
      user-creation: ${KAFKA_TOPIC_USER_CREATION}
    template:
      default-topic: ${spring.kafka.topics.user-creation}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_GROUP_ID}
      properties:
        spring:
          json:
            type:
              mapping: event:com.denisenko.event.UserCreatedEvent