apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ordering.fullname" . }}-db-notification-migration
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      name: db-notification-migration
    spec:
      initContainers:
        - name: init-db-notification-check
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready...";
              until nc -z {{ .Values.notificationService.database.service.name }} {{ .Values.notificationService.database.service.port }}; do
                echo "Notification database not ready yet, waiting...";
                sleep 5;
              done;
      containers:
        - name: db-notification-migration
          image: {{ include "ordering.migration.image" . }}
          env:
            - name: LIQUIBASE_COMMAND_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notificationService.secret.name }}
                  key: db_notification_url
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notificationService.secret.name }}
                  key: db_notification_username
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notificationService.secret.name }}
                  key: db_notification_password
            - name: LIQUIBASE_COMMAND_CHANGELOG_FILE
              value: {{ .Values.migration.volumeMount.mountPath }}
          volumeMounts:
            - name: {{ .Values.migration.volumeMount.name }}
              mountPath: {{ .Values.migration.volumeMount.rootPath }}{{ .Values.migration.volumeMount.mountPath }}
              subPath: changelog_notification
          command: [ "liquibase", "update", "--log-level=DEBUG" ]
      restartPolicy: OnFailure
      volumes:
        - name: {{ .Values.migration.volumeMount.name }}
          configMap:
            name: {{ include "ordering.fullname" . }}-changelog-config