apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ordering.fullname" . }}-deploy-notification
  labels:
    {{- include "ordering.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  replicas: {{ .Values.notificationService.replicaCount }}
  selector:
    matchLabels:
      {{- include "ordering.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: notification-service
        {{- include "ordering.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: notification-service
          image: {{ include "ordering.notificationService.image" . }}
          imagePullPolicy: {{ .Values.notificationService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.notificationService.image.port }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.notificationService.configmap.name }}
                  key: notification_port
            - name: DB_NOTIFICATION_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notificationService.secret.name }}
                  key: db_notification_url
            - name: DB_NOTIFICATION_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notificationService.secret.name }}
                  key: db_notification_username
            - name: DB_NOTIFICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notificationService.secret.name }}
                  key: db_notification_password
            - name: DB_NOTIFICATION_DRIVER_CLASS_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notificationService.secret.name }}
                  key: db_notification_driver_class_name
            - name: JPA_GENERATION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.notificationService.configmap.name }}
                  key: notification_jpa_generation
            - name: KAFKA_TOPIC_ORDER_PLACEMENT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notificationService.secret.name }}
                  key: notification_topic_order_placement
            - name: KAFKA_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notificationService.secret.name }}
                  key: notification_group_id
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.notificationService.kafka.bootstrapServers }}