apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ordering.fullname" . }}-deploy-billing
  labels:
    {{- include "ordering.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  replicas: {{ .Values.billingService.replicaCount }}
  selector:
    matchLabels:
      {{- include "ordering.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: billing-service
        {{- include "ordering.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: billing-service
          image: {{ include "ordering.billingService.image" . }}
          imagePullPolicy: {{ .Values.billingService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.billingService.image.port }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.billingService.configmap.name }}
                  key: billing_port
            - name: DB_BILLING_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.billingService.secret.name }}
                  key: db_billing_url
            - name: DB_BILLING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.billingService.secret.name }}
                  key: db_billing_username
            - name: DB_BILLING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.billingService.secret.name }}
                  key: db_billing_password
            - name: DB_BILLING_DRIVER_CLASS_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.billingService.secret.name }}
                  key: db_billing_driver_class_name
            - name: JPA_GENERATION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.billingService.configmap.name }}
                  key: billing_jpa_generation
            - name: KAFKA_TOPIC_USER_CREATION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.billingService.secret.name }}
                  key: billing_topic_user_creation
            - name: KAFKA_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.billingService.secret.name }}
                  key: billing_group_id
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.billingService.kafka.bootstrapServers }}
