apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ordering.fullname" . }}-deploy-order
  labels:
    {{- include "ordering.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  replicas: {{ .Values.orderService.replicaCount }}
  selector:
    matchLabels:
      {{- include "ordering.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: order-service
        {{- include "ordering.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: order-service
          image: {{ include "ordering.orderService.image" . }}
          imagePullPolicy: {{ .Values.orderService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.orderService.image.port }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.orderService.configmap.name }}
                  key: order_port
            - name: DB_ORDER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.orderService.secret.name }}
                  key: db_order_url
            - name: DB_ORDER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.orderService.secret.name }}
                  key: db_order_username
            - name: DB_ORDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.orderService.secret.name }}
                  key: db_order_password
            - name: DB_ORDER_DRIVER_CLASS_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.orderService.secret.name }}
                  key: db_order_driver_class_name
            - name: JPA_GENERATION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.orderService.configmap.name }}
                  key: order_jpa_generation
            - name: KAFKA_TOPIC_USER_CREATION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.orderService.secret.name }}
                  key: order_topic_user_creation
            - name: KAFKA_TOPIC_ORDER_PLACEMENT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.orderService.secret.name }}
                  key: order_topic_order_placement
            - name: BILLING_SERVICE_URL
              value: "{{ .Values.billingService.service.name }}:{{ .Values.billingService.service.port }}"
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.orderService.kafka.bootstrapServers }}